version: '3.1'
services:
 main:
  image: @CONTROLLER_IMAGE@
  ports:
   - ${UI_PORT:-8080}:8080
   - ${AGENTS_PORT:-50000}:50000
  volumes:
   - @CONTROLLER_ROOT@:/var/jenkins_home
  secrets:
   - jenkins-user
   - jenkins-pass
secrets:
 jenkins-user:
  external: true
 jenkins-pass:
  external: true
